apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: trwo6ewie-python 
  janus-idp.io/tekton: trwo6ewie-python
  backstage.io/kubernetes-id: trwo6ewie-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: trwo6ewie-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml