apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: trwo6ewie-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: trwo6ewie-python 
  name: trwo6ewie-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: trwo6ewie-python 
